### PR TITLE
docs: cleanup

### PR DESCRIPTION
**Pull request by ChandlerFerry**

### CODE REVIEW

**Comment by Nok74** [comment]
There is a problem with synchronization

**Comment by Nok74** [comment]
There is a problem with the synchronization, the connection has been disconnected

**Comment by reall4uk** [comment]
I have exactly the same problem on 2 computers

**Comment by Nok74** [comment]
很奇怪 作者沒有開放回報BUG功能?

**Comment by reall4uk** [comment]
problem not solved ... regular disconnects

**Comment by juantesho** [comment]
hola gente, a mi no me sincroniza. tienen las direcciones de los pares para poder agregarlas manualmente? muchas gracias

**Pull request merged**
